// Examples.GridJs.Simple/ClientApp/vue-gridjs/src/App.vue
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { GridJsSpreadsheet } from 'gridjs-spreadsheet/vue';

const workbookName = 'Sample.xlsx';
const workbook = ref(null);
const error = ref('');
let controller = null;

function createUid() {
  return globalThis.crypto?.randomUUID?.() || `vue-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

function launcherUrl() {
  return import.meta.env.DEV ? 'http://127.0.0.1:8080/' : '/';
}

function openFileUrl() {
  return import.meta.env.DEV
    ? 'http://127.0.0.1:8080/legacy.html'
    : '/legacy.html';
}

async function loadWorkbook() {
  controller?.abort();
  controller = new AbortController();
  workbook.value = null;
  error.value = '';
  try {
    const query = new URLSearchParams({ filename: workbookName, uid: createUid() });
    const response = await fetch(`/GridJs/LoadSpreadsheet?${query}`, { signal: controller.signal });
    if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
    workbook.value = JSON.parse(await response.text());
  } catch (reason) {
    if (reason.name !== 'AbortError') error.value = reason.message || String(reason);
  }
}

function handleReady(instance, adapter) {
  if (adapter.payload?.actname) instance.setActiveSheetByName?.(adapter.payload.actname);
  instance.setActiveCell?.(adapter.payload?.actrow || 0, adapter.payload?.actcol || 0);
  instance.setOpenFileUrl?.(openFileUrl());
  console.log('[GridJS Vue] ready', adapter.payload?.filename);
}

onMounted(loadWorkbook);
onBeforeUnmount(() => controller?.abort());
</script>

<template>
  <main class="editor-shell">
    <header class="demo-bar">
      <a class="back-link" :href="launcherUrl()" aria-label="Back to framework examples">← Examples</a>
      <div class="demo-title">
        <span class="framework-mark" aria-hidden="true">V</span>
        <span><strong>Vue 3</strong><small>{{ workbookName }}</small></span>
      </div>
      <span class="npm-label">npm component</span>
    </header>

    <section class="grid-stage" aria-live="polite">
      <div v-if="!workbook && !error" class="state-panel loading-state" role="status">
        <span class="loading-line wide"></span>
        <span class="loading-line"></span>
        <p>Loading workbook from Spring Boot…</p>
      </div>
      <div v-else-if="error" class="state-panel error-state" role="alert">
        <strong>Workbook could not be loaded</strong>
        <p>{{ error }}</p>
        <button type="button" @click="loadWorkbook">Retry loading</button>
      </div>
      <GridJsSpreadsheet
        v-else
        :data="workbook"
        height="calc(100dvh - 64px)"
        mode="edit"
        locale="en"
        :show-toolbar="true"
        :show-contextmenu="true"
        @ready="handleReady"
        @change="console.log('[GridJS Vue] changed')"
        @error="payload => console.error('[GridJS Vue]', payload)"
      />
    </section>
  </main>
</template>

// Examples.GridJs.Simple/ClientApp/angular-gridjs/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { GridJsSpreadsheetComponent } from 'gridjs-spreadsheet/angular';

type GridJsReadyEvent = {
  instance: any;
  adapter: { payload?: Record<string, any> };
};

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, GridJsSpreadsheetComponent],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
  readonly workbookName = 'Sample.xlsx';
  readonly launcherUrl = window.location.port === '4200' ? 'http://127.0.0.1:8080/' : '/';
  readonly openFileUrl = window.location.port === '4200'
    ? 'http://127.0.0.1:8080/legacy.html'
    : '/legacy.html';
  readonly workbook = signal<Record<string, any> | null>(null);
  readonly error = signal('');

  ngOnInit(): void {
    void this.loadWorkbook();
  }

  async loadWorkbook(): Promise<void> {
    this.workbook.set(null);
    this.error.set('');
    try {
      const uid = globalThis.crypto?.randomUUID?.() || `angular-${Date.now()}-${Math.random().toString(16).slice(2)}`;
      const query = new URLSearchParams({ filename: this.workbookName, uid });
      const response = await fetch(`/GridJs/LoadSpreadsheet?${query}`);
      if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
      this.workbook.set(JSON.parse(await response.text()) as Record<string, any>);
    } catch (reason: unknown) {
      this.error.set(reason instanceof Error ? reason.message : String(reason));
    }
  }

  handleReady(event: GridJsReadyEvent): void {
    const payload = event.adapter.payload;
    if (payload?.['actname']) event.instance.setActiveSheetByName?.(payload['actname']);
    event.instance.setActiveCell?.(payload?.['actrow'] || 0, payload?.['actcol'] || 0);
    event.instance.setOpenFileUrl?.(this.openFileUrl);
    console.log('[GridJS Angular] ready', payload?.['filename']);
  }

  handleError(payload: unknown): void {
    console.error('[GridJS Angular]', payload);
  }

  logChange(): void {
    console.log('[GridJS Angular] changed');
  }
}

<main class="editor-shell">
  <header class="demo-bar">
    <a class="back-link" [href]="launcherUrl" aria-label="Back to framework examples">← Examples</a>
    <div class="demo-title">
      <span class="framework-mark" aria-hidden="true">A</span>
      <span><strong>Angular</strong><small>{{ workbookName }}</small></span>
    </div>
    <span class="npm-label">npm component</span>
  </header>

  <section class="grid-stage" aria-live="polite">
    <div *ngIf="!workbook() && !error()" class="state-panel loading-state" role="status">
      <span class="loading-line wide"></span>
      <span class="loading-line"></span>
      <p>Loading workbook from Spring Boot…</p>
    </div>
    <div *ngIf="error()" class="state-panel error-state" role="alert">
      <strong>Workbook could not be loaded</strong>
      <p>{{ error() }}</p>
      <button type="button" (click)="loadWorkbook()">Retry loading</button>
    </div>
    <gridjs-spreadsheet
      *ngIf="workbook()"
      [data]="workbook()"
      height="calc(100dvh - 64px)"
      mode="edit"
      locale="en"
      [showToolbar]="true"
      [showContextmenu]="true"
      (ready)="handleReady($event)"
      (change)="logChange()"
      (error)="handleError($event)"
    ></gridjs-spreadsheet>
  </section>
</main>
